* 任务（1）：将第二章任务1-3的程序过一遍；
* 任务（2）完成P50实训1和2。

In [1]:
import numpy as np

In [ ]:
# 2.(1)创建一个数值范围为0-1，间隔为0.01的数组；

arr1 = np.arange(0, 1, 0.01)
print(arr1)
# print(arr1.size)

In [ ]:
# 2.(2)创建100个服从正态分布的随机数；

arr2 = np.random.randn(1, 100)
print(arr2)
# print(arr2.size)

In [ ]:
# 2.(3)对创建的两个数组进行四则运算；

# 为了方便观察，重新设置arr1与arr2的shape属性
arr1.shape = 10,10
arr2.shape = 10,10

print('arr1 + arr2 =\n', arr1 + arr2)
print('arr1 - arr2 =\n', arr1 - arr2)
print('arr1 * arr2 =\n', arr1 * arr2)
print('arr1 / arr2 =\n', arr1 / arr2)

In [ ]:
# 2.(4)对创建的随机数组进行简单的统计分析

# 排序
# argsort()
print("原始数据：\n", arr2)
print("argsort()的结果为：\n", arr2.argsort())

# lexsort()
arr1.shape = 1, 100
#print(arr1)
print("lexsort()的结果为：\n", np.lexsort((arr1, arr2))) # sort by arr2

In [ ]:
# 去重
# unique()
print(arr2.size)
print(np.unique(arr2).size)

# 重复
# tile()
print(arr1)
print(np.tile(arr1[0:2], 2))

In [ ]:
# 求和
print("总和:\n", np.sum(arr1))
#print(arr1)
arr1.shape = 10,10
print("横轴和:\n", np.sum(arr1, axis = (1)))
print("纵轴和:\n", np.sum(arr1, axis = (0)))

# 均值
print("总均值:\n", np.mean(arr1))
print("横轴均值:\n", np.mean(arr1, axis = (1)))
print("纵轴均值:\n", np.mean(arr1, axis = (0)))

In [ ]:
# 标准差
print("标准差:\n", np.std(arr1))
# 方差
print("方差:\n", np.var(arr1))

# 最小值
print(np.min(arr1))
print(np.argmin(arr1))

# 最大值
print(np.max(arr1))
print(np.argmax(arr1))

In [5]:
# 3. 棋盘问题

matr1 = np.ones((8,8))
for i in range(8):
    for j in range(8):
        if(i+j)%2 == 0:
            matr1[i,j] = 0
print('国际棋盘对应的矩阵为：\n', matr1)

国际棋盘对应的矩阵为：
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
